kind: pipeline
type: docker
name: archlinux

steps:
- name: build
  image: archlinux
  commands:
  - pacman -Syu --noconfirm
  - pacman -S --noconfirm --needed git libxml2 python3-pip default-jre flex bison libc++
